/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionsFooter: typeof import('./components/ActionsFooter.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    OverlayActivator: typeof import('./components/OverlayActivator.vue')['default']
    RangeSlider: typeof import('./components/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/Slider.vue')['default']
  }
}
