/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/config/attack': RouteRecordInfo<'/config/attack', '/config/attack', Record<never, never>, Record<never, never>>,
    '/config/general': RouteRecordInfo<'/config/general', '/config/general', Record<never, never>, Record<never, never>>,
    '/config/masochist': RouteRecordInfo<'/config/masochist', '/config/masochist', Record<never, never>, Record<never, never>>,
    '/config/mining': RouteRecordInfo<'/config/mining', '/config/mining', Record<never, never>, Record<never, never>>,
    '/config/xp': RouteRecordInfo<'/config/xp', '/config/xp', Record<never, never>, Record<never, never>>,
  }
}
